#!/bin/sh
#
#Lots of credit to http://collaboradev.com/2011/03/31/php-daemons-tutorial/
#

. /etc/rc.d/init.d/functions

prog="sechat-server"
chatserv=${CHATSERV-/path/to/chat/server.php}
proc=${PROC-/var/run/sechat-server.pid}
logfile=${LOGFILE-/var/log/sechat-server.log}
RETVAL=0

start() {
	if [ ! -f $proc ]; then
	    echo -n $"Starting $prog: "
	    daemon  ${chatserv} --logfile=${logfile}
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch $proc
	    echo
	fi
	
	return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
	killproc $chatserv
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f $proc
	echo
        return $RETVAL
}

rh_status() {
    status ${chatserv}
}

# See how we were called.
case "$1" in
    start)
        rh_status >/dev/null 2>&1 && exit 0
        start
        ;;
    stop)
        stop
        ;;
    status)
        rh_status
        ;;
    restart)
        stop
        start
        ;;
    condrestart|try-restart)
        if [ -f $proc ]; then
            stop
            start
        fi
        ;;
    *)
        echo $"Usage: $prog {start|stop|restart|condrestart|try-restart|status|help}"
        RETVAL=2
esac

exit $?
exit $RETVAL
